name: TreasureHunter
version: 2.0
main: me.maartin0.treasurehunt.Main
api-version: 1.19
load: POSTWORLD
authors: [ maartin0 ]

commands:
  hunt:
    usage: "Usage: /<command> [create|delete|scores|mark|confirm|item] <name?>"
    aliases:
      - treasure
      - t
permissions:
  treasurehunt.manage:
    default: op
    description: "Generic manage command"